# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from humanoid_interface_ros/uwbdebug.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class uwbdebug(genpy.Message):
  _md5sum = "a496166c5de3c06085e7947afcc759bc"
  _type = "humanoid_interface_ros/uwbdebug"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 机器人uwb x,y 轴滤波后的效果
float32 robot_uwb_cur_x
float32 robot_uwb_cur_y
float32 robot_uwb_cur_angle
float32 robot_uwb_fir_angle
float32 robot_uwb_fir_x
float32 robot_uwb_fir_y
float32 robot_uwb_avr_x
float32 robot_uwb_avr_y"""
  __slots__ = ['robot_uwb_cur_x','robot_uwb_cur_y','robot_uwb_cur_angle','robot_uwb_fir_angle','robot_uwb_fir_x','robot_uwb_fir_y','robot_uwb_avr_x','robot_uwb_avr_y']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_uwb_cur_x,robot_uwb_cur_y,robot_uwb_cur_angle,robot_uwb_fir_angle,robot_uwb_fir_x,robot_uwb_fir_y,robot_uwb_avr_x,robot_uwb_avr_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(uwbdebug, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_uwb_cur_x is None:
        self.robot_uwb_cur_x = 0.
      if self.robot_uwb_cur_y is None:
        self.robot_uwb_cur_y = 0.
      if self.robot_uwb_cur_angle is None:
        self.robot_uwb_cur_angle = 0.
      if self.robot_uwb_fir_angle is None:
        self.robot_uwb_fir_angle = 0.
      if self.robot_uwb_fir_x is None:
        self.robot_uwb_fir_x = 0.
      if self.robot_uwb_fir_y is None:
        self.robot_uwb_fir_y = 0.
      if self.robot_uwb_avr_x is None:
        self.robot_uwb_avr_x = 0.
      if self.robot_uwb_avr_y is None:
        self.robot_uwb_avr_y = 0.
    else:
      self.robot_uwb_cur_x = 0.
      self.robot_uwb_cur_y = 0.
      self.robot_uwb_cur_angle = 0.
      self.robot_uwb_fir_angle = 0.
      self.robot_uwb_fir_x = 0.
      self.robot_uwb_fir_y = 0.
      self.robot_uwb_avr_x = 0.
      self.robot_uwb_avr_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.robot_uwb_cur_x, _x.robot_uwb_cur_y, _x.robot_uwb_cur_angle, _x.robot_uwb_fir_angle, _x.robot_uwb_fir_x, _x.robot_uwb_fir_y, _x.robot_uwb_avr_x, _x.robot_uwb_avr_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.robot_uwb_cur_x, _x.robot_uwb_cur_y, _x.robot_uwb_cur_angle, _x.robot_uwb_fir_angle, _x.robot_uwb_fir_x, _x.robot_uwb_fir_y, _x.robot_uwb_avr_x, _x.robot_uwb_avr_y,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.robot_uwb_cur_x, _x.robot_uwb_cur_y, _x.robot_uwb_cur_angle, _x.robot_uwb_fir_angle, _x.robot_uwb_fir_x, _x.robot_uwb_fir_y, _x.robot_uwb_avr_x, _x.robot_uwb_avr_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.robot_uwb_cur_x, _x.robot_uwb_cur_y, _x.robot_uwb_cur_angle, _x.robot_uwb_fir_angle, _x.robot_uwb_fir_x, _x.robot_uwb_fir_y, _x.robot_uwb_avr_x, _x.robot_uwb_avr_y,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
