topics:
  - /cmd_vel
  - /joint_cmd.*
  - /cmd.*
  - /sensors_data_raw
  - /sensor_data/.*
  - /joy
  - /joy/set_feedback
  - /kuavo_.*
  - /monitor/.*
  - /odom
  - /pose
  - /quest_joystick_data
  - /rosout
  - /rosout_agg
  - /tf
  - /tf_static
  - /state_estimate/.*
  - /external_wrench
  - /ground_truth/state
  - /humanoid.*
  - /inekf_state/.*
  - /visualization_marker.*
  - /route_plan_pose_array
  - /state_motion_control
  - /kuavo_arm_traj
  - /gait_receiver/.*
  - /SwitchedModelReferenceManager/.*
  - /motor_cmd/.*
  - /sensor_data_motor/.*
